Areas/Telefonia/Controllers/LinhaMovelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IntraGriegHomolog.DAL;
using IntraGriegHomolog.Models;
using IntraGriegHomolog.Models.DropDown;

namespace IntraGriegHomolog.Areas.Telefonia.Controllers 
{
    //Definindo grupo para o acesso 
    [Authorize(Roles = "Telefonia")]
    public class LinhaMovelController : Controller
    {
        private DbIntra db = new DbIntra();
        private LinhaMovelDb LinhaMovelDal = new LinhaMovelDb();

        // Propriedade para guardar o estado da ultima busca para melhor usuabilidade. 
        public List<IN_LINHA_MOVEL> ListaResultPostBack
        {
            get
            {
                return (List<IN_LINHA_MOVEL>)TempData["ListaLinha"];
            }
            set
            {
                TempData["ListaLinha"] = value;
            }
        }
        // Propriedade para guardar todos os parametros.
        public Parametro UltimoParametro
        {
            get
            {
                return (Parametro)TempData.Peek("ListParametros");
            }
            set
            {
                TempData["ListParametros"] = value;
            }
        }


        // GET: LinhaMovel
        public ActionResult Index()
        {

            ViewBag.emp = new SelectList(LinhaMovelDal.ListaEmpresaIndexNull(), "id", "desc");
            List<IN_LINHA_MOVEL> linha = new List<IN_LINHA_MOVEL>();
            return View(linha);
        }

        [HttpPost]
        public ActionResult Index(FormCollection f)
        {

            // grava parametros para consuta de cache
            Parametro p = new Parametro()
            {
                Empresa = Convert.ToInt32(f["emp"]),
                Numero = f["Numero"],
                ICCID = f["ICCID"],
            };

            var lista = LinhaMovelDal.BuscaLinhasMovel(p.Empresa, p.Numero, p.ICCID);
            // verifica se deu erro 
            if (lista.Count == 0)
            {
                TempData["typeMensagem"] = "alert alert-danger";
                TempData["Mensagem"] = "A busca não retornou registros ";
            }

            // cache para parametros e lista 
            UltimoParametro = p;
            ListaResultPostBack = lista;

            ViewBag.emp = new SelectList(LinhaMovelDal.ListaEmpresaIndexNull(), "id", "desc");
            return View(lista);
        }

        public ActionResult VoltarList()
        {
            if (UltimoParametro != null)
            {
                var Ultimabusca = LinhaMovelDal.BuscaLinhasMovel(UltimoParametro.Empresa, UltimoParametro.Numero, UltimoParametro.ICCID);

                // traz todas as empresas e uma campo que mostra todas as empresas 
                ViewBag.emp = new SelectList(LinhaMovelDal.ListaEmpresaIndexNull(), "id", "desc");
                return View("Index", Ultimabusca);
            }
            return RedirectToAction("Index");
        }


        // GET: LinhaMovel/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IN_LINHA_MOVEL linha = db.IN_LINHA_MOVEL.Find(id);
            if (linha == null)
            {
                return HttpNotFound();
            }
            return View(linha);
        }

        // GET: LinhaMovel/Create
        public ActionResult Create()
        {
            ViewBag.EMPID = new SelectList(db.CAD_EMP, "id", "descs");
            ViewBag.situacao = new SelectList(db.cad_Situacao, "id", "descs");
            return View();
        }

        // POST: LinhaMovel/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,EMPID,DESCS,ICCID,tipo_plano,custo_aparelho_plano,situacao")] IN_LINHA_MOVEL linhaMovel)
        {
            if (ModelState.IsValid)
            {
                string[] resultado = LinhaMovelDal.NovaLinha(linhaMovel);
                ResultadoMensagem(resultado);
                return RedirectToAction("Create");
            }
            return View(linhaMovel);
        }

        // GET: LinhaMovel/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IN_LINHA_MOVEL LinhaMovel = db.IN_LINHA_MOVEL.Find(id);
            if (LinhaMovel == null)
            {
                return HttpNotFound();
            }
            ViewBag.EMPID = new SelectList(db.CAD_EMP, "id", "descs", LinhaMovel.EMPID);
            ViewBag.situacao = new SelectList(db.cad_Situacao, "id", "descs", LinhaMovel.situacao);
            return View(LinhaMovel);
        }

        // POST: LinhaMovel/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,EMPID,DESCS,ICCID,tipo_plano,custo_aparelho_plano,situacao")] IN_LINHA_MOVEL linhaMovel)
        {
            string[] resultado = LinhaMovelDal.EditarLinhaMovel(linhaMovel);

            ResultadoMensagem(resultado);

            return RedirectToAction("Edit/" + linhaMovel.ID);
        }

        private void ResultadoMensagem(string[] resultado)
        {
            // mensagem erro - estilos 
            if (resultado[0] == "sucesso")
            {
                TempData["Mensagem"] = resultado[1];
                TempData["typeMensagem"] = resultado[2];
            }
            else
            {
                TempData["Mensagem"] = resultado[1];
                TempData["typeMensagem"] = resultado[2];
            }
        }

        // GET: LinhaMovel/Delete/5
        public ActionResult Delete(long? id)
        {
            // verifica se foi passado id 
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IN_LINHA_MOVEL linhaMovel = db.IN_LINHA_MOVEL.Find(id);
            // verificar a linha existe a  linha 
            if (linhaMovel == null)
            {
                return HttpNotFound();
            }
            return View(linhaMovel);
        }

        // POST: LinhaMovel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            string[] resultado = LinhaMovelDal.DeletarLinha(id);
            ResultadoMensagem(resultado);
            return RedirectToAction("Index");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Telefonia/Views/LinhaMovel/Create.cshtml
@model IntraGriegHomolog.Models.IN_LINHA_MOVEL

@{
    ViewBag.Title = "Nova Linha movel";
}

<h2>Nova linha movel</h2>
@if (TempData["Mensagem"] != null)
{
    <div class="@TempData["typeMensagem"] " role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p>@TempData["Mensagem"]</p>
    </div>
}

<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                @Html.LabelFor(model => model.EMPID, htmlAttributes: new { @class = "control-label " })
                @Html.DropDownList("EMPID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EMPID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-lg-3">
            <div class="form-group">
                @Html.LabelFor(model => model.DESCS, htmlAttributes: new { @class = "control-label " })
                @Html.EditorFor(model => model.DESCS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DESCS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-lg-3">
            <div class="form-group">
                @Html.LabelFor(model => model.ICCID, htmlAttributes: new { @class = "control-label " })
                @Html.EditorFor(model => model.ICCID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ICCID, "", new { @class = "text-danger" })
            </div>

        </div>


        <div class="col-lg-3">
            <div class="form-group">
                @Html.LabelFor(model => model.situacao, htmlAttributes: new { @class = "control-label  " })
                @Html.DropDownList("situacao", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.situacao, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                @Html.LabelFor(model => model.custo_aparelho_plano, htmlAttributes: new { @class = "control-label" })
                @Html.TextAreaFor(model => model.custo_aparelho_plano, new { @class = "form-control", @cols = 80, @rows = 5 })
                @Html.ValidationMessageFor(model => model.custo_aparelho_plano, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-lg-3">
            <div class="form-group">
                @Html.LabelFor(model => model.tipo_plano, htmlAttributes: new { @class = "control-label  " })
                @Html.TextAreaFor(model => model.tipo_plano, new { @class = "form-control", @cols = 80, @rows = 5 })
                @Html.ValidationMessageFor(model => model.tipo_plano, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-lg-3">

        </div>
        <div class="col-lg-3">

        </div>

    </div>

    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-success btn-sm" />
                @Html.ActionLink("Voltar para lista ", "VoltarList", null, new { @class = "btn btn-default btn-sm" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Telefonia/Views/LinhaMovel/Delete.cshtml
@model IntraGriegHomolog.Models.IN_LINHA_MOVEL

@{
    ViewBag.Title = "Deletar";
}

<h2>Deletar</h2>

<h3>Tem certeza que deja excluir isso ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CAD_EMP.descs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CAD_EMP.descs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cad_Situacao.descs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cad_Situacao.descs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DESCS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DESCS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ICCID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ICCID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo_plano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo_plano)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.custo_aparelho_plano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.custo_aparelho_plano)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Deletar" class="btn btn-danger btn-sm" /> |
        @Html.ActionLink("Cancelar", "VoltarList", null, new { @class = "btn btn-default btn-sm" })
    </div>
    }
</div>

Areas/Telefonia/Views/LinhaMovel/Details.cshtml
@model IntraGriegHomolog.Models.IN_LINHA_MOVEL

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CAD_EMP.descs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CAD_EMP.descs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cad_Situacao.descs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cad_Situacao.descs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DESCS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DESCS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ICCID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ICCID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo_plano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo_plano)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.custo_aparelho_plano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.custo_aparelho_plano)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }, new { @class = "glyphicon glyphicon-pencil btn btn-warning btn-sm" })
    @Html.ActionLink("Voltar para lista ", "VoltarList", null, new { @class = "btn btn-default btn-sm" })
</p>

Areas/Telefonia/Views/LinhaMovel/Edit.cshtml
@model IntraGriegHomolog.Models.IN_LINHA_MOVEL

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@if (TempData["Mensagem"] != null)
{
    <div class="@TempData["typeMensagem"] " role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p>@TempData["Mensagem"]</p>
    </div>
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                @Html.LabelFor(model => model.EMPID, htmlAttributes: new { @class = "control-label " })
                @Html.DropDownList("EMPID", null, htmlAttributes: new { @class = "form-control", @style = "font-size:12px" })
                @Html.ValidationMessageFor(model => model.EMPID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-lg-3">
            <div class="form-group">
                @Html.LabelFor(model => model.DESCS, htmlAttributes: new { @class = "control-label " })
                @Html.EditorFor(model => model.DESCS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DESCS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-lg-3">
            <div class="form-group">
                @Html.LabelFor(model => model.ICCID, htmlAttributes: new { @class = "control-label " })
                @Html.EditorFor(model => model.ICCID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ICCID, "", new { @class = "text-danger" })
            </div>

        </div>


        <div class="col-lg-3">
            <div class="form-group">
                @Html.LabelFor(model => model.situacao, htmlAttributes: new { @class = "control-label  " })
                @Html.DropDownList("situacao", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.situacao, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                @Html.LabelFor(model => model.custo_aparelho_plano, htmlAttributes: new { @class = "control-label" })
                @Html.TextAreaFor(model => model.custo_aparelho_plano, new { @class = "form-control", @cols = 80, @rows = 5 })
                @Html.ValidationMessageFor(model => model.custo_aparelho_plano, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-lg-3">
            <div class="form-group">
                @Html.LabelFor(model => model.tipo_plano, htmlAttributes: new { @class = "control-label  " })
                @Html.TextAreaFor(model => model.tipo_plano, new { @class = "form-control", @cols = 80, @rows = 5 })
                @Html.ValidationMessageFor(model => model.tipo_plano, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-lg-3">

        </div>
        <div class="col-lg-3">

        </div>

    </div>

    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-success btn-sm" />
                @Html.ActionLink("Detalhes ", "Details", new { id = Model.ID }, new { @class = "btn btn-primary btn-sm" })
                @Html.ActionLink("Voltar para lista ", "VoltarList", null, new { @class = "btn btn-default btn-sm" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

  

}

Areas/Telefonia/Views/LinhaMovel/Index.cshtml
@model IEnumerable<IntraGriegHomolog.Models.IN_LINHA_MOVEL>

@{
    ViewBag.Title = "Linha Movel";
}

<h2>Linha Movel</h2>


@*Mensagem erro*@
@if (TempData["Mensagem"] != null)
{
    <div class="@TempData["typeMensagem"] " role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p>@TempData["Mensagem"]</p>
    </div>
}
 
<hr />
<table>
    @using (Html.BeginForm("index", "LinhaMovel", FormMethod.Post))
    {
        <tr>
            <th style="padding-right: 10px;"> @Html.DropDownList("emp", (IEnumerable<SelectListItem>)ViewBag.emp, new { @class = "form-control", @style = "font-size:12px", @id = "emp", @onchange = "ValorDrop(this.value)" })  </th>
            <th style="padding-right: 10px;"> @Html.Editor("Numero", new { htmlAttributes = new { @class = "form-control", @placeholder = "Nº Telefônico " } })</th>
            <th style="padding-right: 10px;"> @Html.Editor("ICCID", new { htmlAttributes = new { @class = "form-control", @placeholder = "ICCID" } })        </th>
            <th style="padding-right: 10px;"> <button type="submit" class="glyphicon glyphicon-search  btn btn-primary btn-sm"></button>                            </th>
        </tr>
    }
</table>
<hr />
<p>
    @Html.ActionLink(" Novo", "Create", null, new { @class = "glyphicon glyphicon-plus btn btn-primary btn-sm" })
</p>
<div style="display:@( Model.Count() > 0 ? "block" : "none")">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CAD_EMP.descs)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DESCS)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ICCID)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr class="@(item.situacao.Equals(2)? "danger" : " ")">
                <td>
                    @Html.DisplayFor(modelItem => item.CAD_EMP.descs)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DESCS)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ICCID)
                </td>

                <td>
                    @Html.ActionLink(" ", "Edit", new { id = item.ID }, new { @class = "glyphicon glyphicon-pencil btn btn-warning btn-sm" })
                    @Html.ActionLink(" ", "Details", new { id = item.ID }, new { @class = "glyphicon glyphicon-eye-open btn btn-primary btn-sm" })
                    @Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "glyphicon glyphicon glyphicon-remove  btn btn-danger btn-sm" })
                </td>
            </tr>
        }

    </table>
</div>