Controllers/ComputersControl/PrinterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IntraGriegHomolog.DAL;
using IntraGriegHomolog.Models;
using IntraGriegHomolog.Models.DropDown;

namespace IntraGriegHomolog.Controllers.ComputersControl
{
    [Authorize(Roles = "TI")]
    public class PrinterController : Controller
    {
        private DbIntra db = new DbIntra();
        private PrinterDb PrinterDb = new PrinterDb();

        // parametro para cache
        public List<IN_PRINTER> ListPrinterPostBack
        {
            get
            {
                return (List<IN_PRINTER>)TempData["ListPrinter"];
            }
            set
            {
                TempData["ListPrinter"] = value;
            }

        }

        public Parametro UltimoParametro
        {

            get
            {
                return (Parametro)TempData.Peek("UltimoParametro");

            }
            set
            {
                TempData["UltimoParametro"] = value;
            }

        }

        public ActionResult VoltarList()
        {
            if (UltimoParametro != null)
            {
                var UltimaBuscaAtualizada = PrinterDb.BuscaGenericaPrinter(UltimoParametro.Empresa, UltimoParametro.UserName, UltimoParametro.ip, UltimoParametro.Departamento);
                ViewBag.emp = new SelectList(PrinterDb.ListaEmpresaIndexNull(), "id", "desc");
                return View("Index", UltimaBuscaAtualizada);
            }

            return RedirectToAction("Index");
        }

        // GET: Printer
        public ActionResult Index()
        {
            ViewBag.emp = new SelectList(PrinterDb.ListaEmpresaIndexNull(), "id", "desc");
            List<IN_PRINTER> list = new List<IN_PRINTER>();

            return View(list);
        }

        [HttpPost]
        public ActionResult Index(FormCollection f)
        {
            int Departamento = (f["Departamentos"] == "-1" ? 0 : Convert.ToInt32(f["departmentsDropdown"]));
            var busca = PrinterDb.BuscaGenericaPrinter(Convert.ToInt32(f["emp"]), f["departamentos"], f["Ip"] , Departamento);

            Parametro parametros = new Parametro
            {
                Empresa = Convert.ToInt32(f["emp"]),
                UserName = f["departamentos"],
                Departamento = Departamento ,
                ip = f["Ip"]

            };

            if (busca.Count == 0)
            {
                TempData["TypeErro"] = "alert alert-danger";
                TempData["erro"] = "A busca não retornou registros ";
            }

            // parametro para cache
            UltimoParametro = parametros;
            ListPrinterPostBack = busca;

            ViewBag.emp  = new SelectList(PrinterDb.ListaEmpresaIndexNull(), "id", "desc");

            return View("index", busca);
 
        }

        private void ResultadoMensagem(string[] resultado)
        {
            // mensagem erro - estilos 
            if (resultado[0] == "sucesso")
            {
                TempData["Mensagem"] = resultado[1];
                TempData["typeMensagem"] = resultado[2];
            }
            else
            {
                TempData["Mensagem"] = resultado[1];
                TempData["typeMensagem"] = resultado[2];
            }
        }


        // GET: Printer/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IN_PRINTER iN_PRINTER = db.IN_PRINTER.Find(id);
            if (iN_PRINTER == null)
            {
                return HttpNotFound();
            }
            return View(iN_PRINTER);
        }

        // GET: Printer/Create
        public ActionResult Create()
        {
            ViewBag.DEPTID = new SelectList(PrinterDb.BuscarDepartamento(1), "id", "desc");
            ViewBag.EMPID = new SelectList(db.CAD_EMP, "id", "descs");
            ViewBag.MODEL = new SelectList(db.CAD_ITEM.Where(x => x.typeID == 7), "id", "descs");
            ViewBag.situacao = new SelectList(db.cad_Situacao, "id", "descs");
            return View();
        }

        // POST: Printer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,SERIAL_NO,MODEL,EMPID,DEPTID,IP,APELIDO,info,situacao")] IN_PRINTER printer)
        {
           
                string[] resultado = PrinterDb.NovaImpressora(printer);
            // valida sstatus e mostrar para  o usuario
                ResultadoMensagem(resultado);

            return RedirectToAction("Create");
        }

        // GET: Printer/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IN_PRINTER printer = db.IN_PRINTER.Find(id);
            if (printer == null)
            {
                return HttpNotFound();
            }
            ViewBag.DEPTID = new SelectList(PrinterDb.BuscarDepartamento(printer.EMPID), "id", "desc", printer.DEPTID);
            ViewBag.EMPID = new SelectList(db.CAD_EMP, "id", "descs", printer.EMPID);
            ViewBag.MODEL = new SelectList(db.CAD_ITEM.Where(x => x.typeID == 7), "id", "descs", printer.MODEL);
            ViewBag.situacao = new SelectList(db.cad_Situacao, "id", "descs", printer.situacao);

            return View(printer);
        }


        public JsonResult GetDepartamentos(int p)
        {
            // pega os usuarios que estão com os ramais nulos PRONTO PARA O USO E REFINANDO PELA A EMPRESA 
            return Json(from v in db.CAD_DEPT
                        where v.emp == p
                        select new
                        {
                            id = v.id,
                            descs = v.descs
                        }, JsonRequestBehavior.AllowGet);
        }


        // POST: Printer/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,SERIAL_NO,MODEL,EMPID,DEPTID,IP,APELIDO,info,situacao")] IN_PRINTER printer)
        {
            string[] resultado = PrinterDb.EditarPrinter(printer);
            ResultadoMensagem(resultado);

            return RedirectToAction("Edit/" + printer.ID);
            
        }

        // GET: Printer/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IN_PRINTER iN_PRINTER = db.IN_PRINTER.Find(id);
            if (iN_PRINTER == null)
            {
                return HttpNotFound();
            }
            return View(iN_PRINTER);
        }

        // POST: Printer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            string[] resultado = PrinterDb.DeletarPrint(id);
            ResultadoMensagem(resultado);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Printer/Create.cshtml
@model IntraGriegHomolog.Models.IN_PRINTER

@{
    ViewBag.Title = "Nova impressora";
}
@*//nome para o ajax URL => /Ti/Inventario*@

<script>
    function ValorDrop(valor) {
        $.ajax({
            type: "GET",
            url: "/Inventario/Printer/GetDepartamentos?p=" + valor,
            data: "{}",
            success: function (data) {
                var row = '<option value=>SEM DEPARTAMENTO</option>';
                for (var i = 0; i < data.length; i++) {
                    row += '<option value="' + data[i].id + '">' + data[i].descs + '</option>';
                }
                $("#DEPTID").html(row);
            }
        });
    }

</script>

<h2>Nova impressora</h2>

@if (TempData["Mensagem"] != null)
{
    <div class="@TempData["typeMensagem"] " role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p>@TempData["Mensagem"]</p>
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.SERIAL_NO, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.SERIAL_NO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SERIAL_NO, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.MODEL, htmlAttributes: new { @class = "control-label " })
                    @Html.DropDownList("MODEL", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MODEL, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.EMPID, htmlAttributes: new { @class = "control-label " })
                    @Html.DropDownList("EMPID", null, htmlAttributes: new { @class = "form-control", @onchange = "ValorDrop(this.value)" })
                    @Html.ValidationMessageFor(model => model.EMPID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.DEPTID, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownList("DEPTID", null, htmlAttributes: new { @class = "form-control", @id = "DEPTID" })
                    @Html.ValidationMessageFor(model => model.DEPTID, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.IP, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.IP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IP, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.APELIDO, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.APELIDO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.APELIDO, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.situacao, htmlAttributes: new { @class = "control-label " })
                    @Html.DropDownList("situacao", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.situacao, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.info, htmlAttributes: new { @class = "control-label " })
                    @Html.TextAreaFor(model => model.info, new { @class = "form-control", @cols = 80, @rows = 5 })
                    @Html.ValidationMessageFor(model => model.info, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-success  " />
                @Html.ActionLink("Cancelar ", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Printer/Delete.cshtml
@model IntraGriegHomolog.Models.IN_PRINTER

@{
    ViewBag.Title = "Delete";
}

<h2>Deletar</h2>

<h3>Tem certeza que deseja excluir isso ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CAD_DEPT.descs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CAD_DEPT.descs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CAD_EMP.descs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CAD_EMP.descs)
        </dd>

        <dt>
            Modelo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CAD_ITEM.descs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cad_Situacao.descs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cad_Situacao.descs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SERIAL_NO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SERIAL_NO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.APELIDO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.APELIDO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.info)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.info)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger btn-sm" /> |
        @Html.ActionLink("Voltar para lista ", "VoltarList", null, new { @class = "btn btn-default  btn-sm " })

    </div>
    }
</div>

Views/Printer/Details.cshtml
@model IntraGriegHomolog.Models.IN_PRINTER

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>IN_PRINTER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CAD_DEPT.descs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CAD_DEPT.descs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CAD_EMP.descs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CAD_EMP.descs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CAD_ITEM.descs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CAD_ITEM.descs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cad_Situacao.descs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cad_Situacao.descs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SERIAL_NO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SERIAL_NO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.APELIDO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.APELIDO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.info)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.info)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Printer/Edit.cshtml
@model IntraGriegHomolog.Models.IN_PRINTER

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

    @*//nome para o ajax URL => /Ti/Inventario*@

<script>
    function ValorDrop(valor) {
        $.ajax({
            type: "GET",
            url: "/Inventario/Printer/GetDepartamentos?p=" + valor,
            data: "{}",
            success: function (data) {
                var row = '<option value=>SEM DEPARTAMENTO</option>';
                for (var i = 0; i < data.length; i++) {
                    row += '<option value="' + data[i].id + '">' + data[i].descs + '</option>';
                }
                $("#DEPTID").html(row);
            }
        });
    }

</script>

@if (TempData["Mensagem"] != null)
{
    <div class="@TempData["typeMensagem"] " role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p>@TempData["Mensagem"]</p>
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.SERIAL_NO, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.SERIAL_NO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SERIAL_NO, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.MODEL, htmlAttributes: new { @class = "control-label " })
                    @Html.DropDownList("MODEL", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MODEL, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.EMPID, htmlAttributes: new { @class = "control-label " })
                    @Html.DropDownList("EMPID", null, htmlAttributes: new { @class = "form-control", @onchange = "ValorDrop(this.value)" })
                    @Html.ValidationMessageFor(model => model.EMPID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.DEPTID, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownList("DEPTID", null, htmlAttributes: new { @class = "form-control", @id = "DEPTID" })
                    @Html.ValidationMessageFor(model => model.DEPTID, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.IP, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.IP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IP, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.APELIDO, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.APELIDO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.APELIDO, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.situacao, htmlAttributes: new { @class = "control-label " })
                    @Html.DropDownList("situacao", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.situacao, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.info, htmlAttributes: new { @class = "control-label " })
                    @Html.TextAreaFor(model => model.info, new { @class = "form-control", @cols = 80, @rows = 5 })
                    @Html.ValidationMessageFor(model => model.info, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-success btn-sm" />
                @Html.ActionLink("Deletar", "delete", new { id = Model.ID }, new { @class = "btn btn-danger  btn-sm " })
                @Html.ActionLink("Voltar para lista ", "VoltarList", null, new { @class = "btn btn-default  btn-sm " })

            </div>
        </div>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Printer/Index.cshtml
@model IEnumerable<IntraGriegHomolog.Models.IN_PRINTER>

@{
    /**/

    ViewBag.Title = "Impressoras";
}

<h2>Impressoras</h2>
@if (TempData["Mensagem"] != null)
{
    <div class="@TempData["typeMensagem"] " role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p>@TempData["Mensagem"]</p>
    </div>
}

<hr />
@using (Html.BeginForm("Index", "Printer", FormMethod.Post))
{
    <table>
        @Html.AntiForgeryToken()
        <tr>
            <th style="padding-right: 25px;"> @Html.DropDownList("emp", (IEnumerable<SelectListItem>)ViewBag.emp, new { @class = "form-control", @id = "emp", @onchange = "ValorDrop(this.value)" })  </th>
            <th style="padding-right: 25px;"> @Html.Editor("departamentos", new { htmlAttributes = new { @class = "form-control", @placeholder = "Departamentos" } })          </th>
            <th style="padding-right: 25px;"> @Html.Editor("Ip", new { htmlAttributes = new { @class = "form-control", @placeholder = "IP", } })</th>

            <th style="padding-right: 10px;"> <button type="submit" class="glyphicon glyphicon-search  btn btn-primary btn-sm"></button>                            </th>
        </tr>
    </table>
    <hr />
}
@Html.ActionLink(" Novo", "Create", null, new { @class = "glyphicon glyphicon-plus btn btn-primary btn-sm" })
<br /><br />
<div style="display:@(Model.Count() > 0 ?"block":"none")">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CAD_DEPT.descs)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CAD_EMP.descs)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SERIAL_NO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.APELIDO)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr class="@(item.situacao.Equals(2)?"danger":"")">
                <td>
                    @Html.DisplayFor(modelItem => item.CAD_DEPT.descs)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CAD_EMP.descs)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SERIAL_NO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.APELIDO)
                </td>
                <td>
                    @Html.ActionLink(" ", "Edit", new { id = item.ID }, new { @class = "glyphicon glyphicon-pencil btn btn-warning btn-sm" }) |
                    @Html.ActionLink("Historico", "Historico", new { id = item.ID }, new { @class = " btn btn-primary btn-sm" })
                </td>
            </tr>


        }

    </table>
</div>